/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testing_cat;

import cat.Cat;
import cat.CatBuilder;
import errors.MouseEscapedException;
import mouse.Mouse;

import static java.lang.Double.parseDouble;

public class App {

    public static void main(String[] args) {
        for (String item : args) {
            System.out.println(item);
        }

        double catX = parseDouble(args[0]);
        double catY = parseDouble(args[1]);

        double mouseX = parseDouble(args[2]);
        double mouseY = parseDouble(args[3]);

        Cat cat = new CatBuilder().at(catX, catY).assemble();
        Mouse mouse = new Mouse(mouseX, mouseY);


        if (cat.catchMouse(mouse)) {
            System.out.println("Mouse successfully caught");
        } else {
            throw new MouseEscapedException(mouse);
        }
    }
}
